# how ofter the cache respond of a respondd request is calculated
data_interval = "3m"

batman = "[::1]:33123"

[[listen]]
address   = "ff02::2:1001"
interface = ""
port      = 1001

[defaults]
node_id  = ""
hostname = ""
site_code = "ffhb"
domain_code = ""
vpn = false

[defaults.location]
latitude  = 53.112446246
longitude = 8.734087944


# if divergent configuration of defaults are wanted by respond on interface/zones example with bat0
[zones.bat0]
node_id  = ""
hostname = ""
