# how ofter the cache respond of a respondd request is calculated
data_interval = "3m"

batman = ["bat03", "bat04"]
babel  = "[::1]:33123"

[[listen]]
address   = "ff02::2:1001"
interface = "bat03"
port      = 1001

[defaults]
node_id  = ""
hostname = ""
site_code = "ffhb"
domain_code = ""
vpn = false
interface_mac = "eth0"
interfaces_traffic = [ "eth0" ]
interfaces_address = [ "br-ffhb", "eth0" ]

[defaults.location]
latitude  = 53.112446246
longitude = 8.734087944

# if divergent configuration of defaults are wanted by respond on interface/zones example with bat0
[zones.bat03]
node_id  = ""
hostname = ""
#...
